language: node_js
node_js:
  - "8"
dist: trusty
addons:
  sonarcloud:
    organization: $sonarcloud_organization_key
    token: $sonarcloud_token
    branches:
      - master
      - next
  apt:
    packages:
    - lftp
  firefox: latest
cache:
  yarn: true
  directories:
    - node_modules
matrix:
  fast_finish: true
before_install:
  - pip install --user codecov
  - export XSTR_VERSION=$(node -p "require('./package.json').version")
script:
  - yarn webdriver-manager update
  - yarn lint
  - yarn test
  - yarn e2e
  - sonar-scanner -Dsonar.projectVersion=$XSTR_VERSION
after_success:
  - sh scripts/build-ng.sh
  - codecov
  - sh scripts/patch-gh-pages.sh
  - sh scripts/package-www.sh
before_deploy:
  - echo "before deploy steps"
deploy:
  - provider: pages
    local_dir: www
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: next
  - provider: script
    skip_cleanup: true
    script: sh scripts/deploy-prod.sh
    on:
      branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: client.xstr.me-*.tar.gz
    skip_cleanup: true
    on:
      tags: true
  - provider: script    
    script: sh scripts/deploy-desktop.sh
    skip_cleanup: true
    on:
      tags: true
  - provider: script    
    script: sh scripts/deploy-mobile.sh
    skip_cleanup: true
    on:
      tags: true
