language: node_js
node_js:
  - "8"
dist: trusty
addons:
  chrome: stable
before_install:
  - pip install --user codecov
after_success:
  - codecov
deploy:
  local_dir: dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master