language: node_js
node_js:
  - "8"
dist: trusty
addons:
  sonarcloud:
    organization: $sonarcloud_organization_key
    token: $sonarcloud_token
  apt:
    packages:
    - lftp
  chrome: stable
before_install:
  - pip install --user codecov
script:
  - npm test
  - sonar-scanner
  - sh scripts/build-ng.sh
after_success:
  - codecov
  - sh scripts/patch-gh-pages.sh
deploy:
  - provider: pages
    local_dir: www
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: next
  - provider: script
    skip_cleanup: true
    script: sh scripts/deploy-prod.sh
    on:
      branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    local_dir: www
    skip_cleanup: true
    on:
      tags: true
