language: node_js
node_js:
  - "8"
dist: trusty
addons:
  sonarcloud:
    organization: $sonarcloud_organization_key
    token: $sonarcloud_token
  apt:
    packages:
    - lftp
  firefox: latest
cache:
  yarn: true
  directories:
    - node_modules
matrix:
  fast_finish: true
before_install:
  - pip install --user codecov
  - export XSTR_VERSION=$(node -p "require('./package.json').version")
after_success:
  - sonar-scanner -Dsonar.projectVersion=$XSTR_VERSION -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$sonarcloud_token -Dsonar.organization=guedouari-github -Dsonar.branch.name=$TRAVIS_BRANCH
  - sh scripts/build-ng.sh
  - codecov
  - sh scripts/patch-gh-pages.sh
  - sh scripts/package-www.sh
before_deploy:
  - echo "before deploy steps ..."
