language: node_js
node_js:
  - "8"
dist: trusty
addons:
  apt:
    packages:
    - lftp
  chrome: stable
before_install:
  - pip install --user codecov
script:
  - npm test
  - npm run build
after_success:
  - codecov
  - cp $TRAVIS_BUILD_DIR/www/index.html $TRAVIS_BUILD_DIR/www/404.html
deploy:
  - provider: pages
    local_dir: www
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: next
  - provider: script
    skip_cleanup: true
    script: lftp -u $FTP_USER,$FTP_PASSWORD $FTP_SERVER  -e "rm -r www; exit"
    on:
      branch: next
